import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/legacy/image'
import profilepic from '../public/mustafapppppp.jpg'
import react from '../public/reactlogo.png'
import proje1 from '../public/Ekran Resmi 2022-11-02 20.42.26.png'
import proje2 from '../public/Ekran Resmi 2022-11-02 20.43.08.png'
import proje3 from '../public/Ekran Resmi 2022-11-02 20.44.32.png'
import proje4 from '../public/Ekran Resmi 2022-11-02 20.45.46.png'
import proje5 from '../public/Ekran Resmi 2022-11-02 20.50.51.png'
import proje6 from '../public/Ekran Resmi 2022-11-02 20.55.35.png'
import { useState } from "react";




export default function Home() {

  const [darkMode, setDarkMode] = useState(false); 
  const css = { width: '100%', height: 'auto' }
  return (
    <>
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Mustafa SAĞLAM Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 flex justify-between">
            <h1 className="text-xl font-burtons ">MyPortfolio</h1>
            <ul className="flex items-center ">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl"/>
              </li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav> 
<div className="text-center p-10">
  <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Mustafa SAĞLAM</h2>
  <h3 className="text-2xl py-2 md:text-3xl">Junior Frontend Developer</h3>
  <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">Lorem ipsum, dolor sit amet consectetur adipisicing elit. At quibusdam necessitatibus aspernatur libero magni, culpa saepe incidunt esse dolore similique!</p>
</div>
<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
<AiFillTwitterCircle />
<AiFillLinkedin />
<AiFillYoutube />
</div>
<div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
<Image alt="" src={profilepic} layout="fill" objectFit="cover" />
</div>
        </section>

<section>
  <div>
    <h3 className="text-3xl py-1">My Projects</h3>
    <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo repellendus soluta aut deserunt dolor id.</p>
  </div>
  <div className="lg:flex gap-10">
    <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
      <Image alt="" src={react} width={100} height={100} />
      <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Desings</h3>
      <p className="py-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam, atque.</p>
    <h4 className="py-4 text-teal-600">Tools</h4>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    
    </div>
    <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
      <Image alt="" src={react} width={100} height={100} />
      <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Desings</h3>
      <p className="py-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam, atque.</p>
    <h4 className="py-4 text-teal-600">Tools</h4>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    
    </div>
    <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
      <Image alt="" src={react} width={100} height={100} />
      <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Desings</h3>
      <p className="py-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam, atque.</p>
    <h4 className="py-4 text-teal-600">Tools</h4>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    <p className="text-gray-800 py-1">photoshop</p>
    
    </div>



  </div>
</section>
<section>
  <div>
    <h3 className="text-3xl py-1">Portofolio</h3>
  </div>
  <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje1} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje2} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje3} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje4} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje5} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>
    <div className="basis-1/3 flex-1">
      <Image alt="" src={proje6} className="rounded-lg object-cover" sizes="100vw" style={css} layout="responsive" /> 
      </div>

  </div>
</section>

      </main>
      </div>
    </>
  )
}
